#!groovy
env.BRANCH_NAME = "release/v9.9.9"
cfg = jplConfig("jplCloseReleaseTest", "backend")
cfg.promoteBuild.enabled = true

pipeline {

    agent { label "master" }

    stages {
        stage ("jplCloseRelease Test - Initialize") {
            steps  {
                echo "jplCloseRelease Test - Initialize"
                sh "printenv"
                println cfg
                jplStart(cfg)
            }
        }
        stage ("jplCloseRelease Test - Prepare test") {
            steps {
                echo "jplCloseRelease Test - Prepare test"
                sh "git merge origin/master; git push"
                deleteDir()
            }
        }
        stage ("jplCloseRelease Test - Close Release") {
            steps {
                echo "jplCloseRelease Test - Closing release: ${cfg.releaseTag}, short one ${cfg.releaseTagNumber}"
                jplCloseRelease(cfg)
            }
        }
    }

    options {
        timestamps()
        ansiColor("xterm")
    }
}