#!groovy
env.BRANCH_NAME = "release/v9.9.9"
cfg = jplConfig("jplCloseReleaseTest", "backend", "", [hipchat: "", slack: "", email: ""])
cfg.promoteBuild.enabled = true
cfg.changelog.firstTag = "v0.8.0"

pipeline {

    agent any

    stages {
        stage ("Initialize") {
            steps  {
                jplStart(cfg)
            }
        }
        stage ("Close Release") {
            steps {
                echo "Closing release: ${cfg.releaseTag}"
                jplCloseRelease(cfg)
            }
        }
    }

    options {
        timestamps()
        ansiColor("xterm")
        skipDefaultCheckout()
    }
}