#!groovy
cfg = jplConfig("jplCloseReleaseTest", "backend", "", [hipchat: "", slack: "", email: ""])
cfg.promoteBuild.enabled = true
cfg.BRANCH_NAME = "release/v9.9.9"
cfg.changelog.firstTag = "v0.8.0"

pipeline {

    agent any

    stages {
        stage ("Checkout SCM") {
            steps  {
                jplCheckoutSCM(cfg)
            }
        }
        stage ("Close Release") {
            steps {
                jplCloseRelease(cfg)
            }
        }
    }

    options {
        timestamps()
        ansiColor("xterm")
        skipDefaultCheckout()
    }
}