#!groovy
env.BRANCH_NAME = "hotfix/v9.9.9-hotfix-1"
cfg = jplConfig("jplCloseHotfixHappyTest", "backend")
cfg.promoteBuild.enabled = true

pipeline {

    agent any

    stages {
        stage ("jplCloseHotfixHappy Test - Initialize") {
            steps  {
                echo "jplCloseHotfixHappy Test - Initialize"
                sh "printenv"
                println cfg
                jplStart(cfg)
            }
        }
        stage ("jplCloseHotfixHappy Test - Prepare test") {
            steps {
                echo "jplCloseHotfixHappy Test - Prepare test"
                sh "git merge origin/master; git push"
                deleteDir()
            }
        }
        stage ("jplCloseHotfixHappy Test - Close Hotfix") {
            steps {
                echo "jplCloseHotfixHappy Test - Closing hotfix: ${cfg.releaseTag}, short one ${cfg.releaseTagNumber}"
                jplCloseRelease(cfg)
            }
        }
    }

    options {
        timestamps()
        ansiColor("xterm")
        skipDefaultCheckout()
    }
}